apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- service-account.yaml
- role-create.yaml
- ns.yaml
- redis-stateful.yaml
- payment.yaml
- subscription.yaml
- nginx-ingress.yaml
- cluster-monitoring-config.yaml
- monitor.yaml


secretGenerator:
- name: redis-conf
  namespace: sns
  files: 
    - secrets/redis.conf
    - secrets/redis_password
# - name: # TLS Cert Name
#  namespace: sns
#  type: "kubernetes.io/tls"
#  files:
#    - tls.crt= # TLS certificate file
#    - tls.key= # TLS Key file