apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: sns
data:
  config.json: |
    {
      "server_port": 3000,
      "redis_host": "redis",
      "redis_port": 6379
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: sns
  labels:
    app: payment
spec:
  selector:
    matchLabels:
      app: payment
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: sns-payment:v1.0.3
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi      
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /probes/liveness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /probes/readiness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: NODE_ENV
            value: "production"
          - name: CONFIG_DIR
            value: "/opt/sns/app/config"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-conf
                key: redis_password
        imagePullPolicy: "Never"  
        volumeMounts:
        - name: payment-config
          mountPath: "/opt/sns/config"
      volumes:
      - name: payment-config
        configMap:
          name: payment-config      
        
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: sns
  labels:
    app: payment
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: payment
