apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: sns
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0.4-alpine
 #       args: ["usr/local/etc/redis/redis.conf"]
        resources:
           limits:
             memory: "1.5Gi"
           requests:
             memory: "1.5Gi"
        ports:
        - name: client
          containerPort: 6379
        - name: master
          containerPort: 16379
        livenessProbe:
         tcpSocket:
           port: client # named port
         initialDelaySeconds: 30
         timeoutSeconds: 5
         periodSeconds: 5
         failureThreshold: 5
         successThreshold: 1
        readinessProbe:
         exec:
           command:
           - redis-cli
           - ping
         initialDelaySeconds: 10
         timeoutSeconds: 5
         periodSeconds: 3
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: conf
          mountPath: "/usr/local/etc/redis"
        - name: redis-data
          mountPath: /data
          readOnly: false
      volumes:
      - name: conf
        secret:
          secretName: redis-conf
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: master
  selector:
    app: redis