apiVersion: v1
kind: ConfigMap
metadata:
  name: subscription-config
  namespace: sns
data:
  config.json: |
    {
      "server_port": 3001,
      "redis_host": "redis",
      "redis_port": 6379,
      "paymentUrlBase": "http://payment:3000",
      "amountPerMonth": 25.00
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
  namespace: sns
  labels:
    app: subscription
spec:
  selector:
    matchLabels:
      app: subscription
  replicas: 1
  template:
    metadata:
      labels:
        app: subscription
    spec:
      serviceAccountName: sa-nomount
      securityContext:
        runAsUser: 1000591000
        fsGroup: 1000590000
        runAsGroup: 1000590000
      containers:
      - name: subscription
        image: lmtbelmonte/sns-subscription:v1.0.2
        securityContext:
          runAsUser: 1000591000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 3001
        env:
          - name: NODE_ENV
            value: "production"
          - name: CONFIG_DIR
            value: "/opt/sns/config"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-conf
                key: redis_password
        imagePullPolicy: "IfNotPresent"
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /probes/liveness
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /probes/readiness
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 30
        volumeMounts:
        - name: subscription-config
          mountPath: "/opt/sns/config"
      volumes:
      - name: subscription-config
        configMap:
          name: subscription-config
---
apiVersion: v1
kind: Service
metadata:
  name: subscription
  namespace: sns
  labels:
    app: subscription
spec:
  ports:
  - port: 3001
    targetPort: 3001
    name: web
  selector:
    app: subscription
